import type { StoreConfig, Category, Product, SliderBanner, Review, Brand } from '@/types'

export const mockConfig: StoreConfig = {
    name: 'RETROVERSE',
    logo: null,
    primaryColor: '#E63946',
    bgColor: '#0a0a0a',
    cardBg: '#141414',
    textColor: '#f1f1f1',
    headerBg: '#0a0a0a',
    footerBg: '#0d0d0d',
    whatsapp: '5491112345678',
    instagram: 'https://instagram.com/retroverse',
    facebook: 'https://facebook.com/retroverse',
    tiktok: null,
    phone: '+54 9 11 1234-5678',
    tagline: 'Videojuegos retro y coleccionables',
}

export const mockCategories: Category[] = [
    { id: '1', name: 'Videojuegos', slug: 'videojuegos', order: 1, visible: true },
    { id: '2', name: 'Consolas', slug: 'consolas', order: 2, visible: true },
    { id: '3', name: 'Amiibos', slug: 'amiibos', order: 3, visible: true },
    { id: '4', name: 'Accesorios', slug: 'accesorios', order: 4, visible: true },
    { id: '5', name: 'Figuras', slug: 'figuras', order: 5, visible: true },
]

export const mockSliders: SliderBanner[] = [
    {
        id: '1',
        image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&h=450&fit=crop',
        order: 1,
        active: true,
    },
    {
        id: '2',
        image: 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=1200&h=450&fit=crop',
        order: 2,
        active: true,
    },
    {
        id: '3',
        image: 'https://images.unsplash.com/photo-1600861194802-a2b11076bc51?w=1200&h=450&fit=crop',
        order: 3,
        active: true,
    },
]

export const mockProducts: Product[] = [
    {
        id: '1',
        name: 'The Legend of Zelda: Ocarina of Time',
        price: 8500,
        description: 'Cartucho original en excelente estado. Funciona perfecto en consola original y clones.',
        images: ['https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=400&h=400&fit=crop'],
        categoryId: '1',
        console: 'Nintendo 64',
        condition: 'good',
        complete: false,
        region: 'NTSC',
        status: 'available',
        tags: ['featured', 'offer'],
        createdAt: new Date('2026-01-15'),
    },
    {
        id: '2',
        name: 'Super Nintendo SNES Clásica',
        price: 45000,
        description: 'Consola en perfecto estado estético y funcional. Incluye cables y dos controles originales.',
        images: ['https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=400&fit=crop'],
        categoryId: '2',
        console: 'SNES',
        condition: 'like_new',
        complete: true,
        region: 'NTSC',
        status: 'available',
        tags: ['new', 'featured'],
        createdAt: new Date('2026-01-20'),
    },
    {
        id: '3',
        name: 'Link Amiibo - Breath of the Wild',
        price: 3200,
        description: 'Amiibo sellado de fábrica. Caja en perfectas condiciones sin golpes ni dobleces.',
        images: ['https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=400&h=400&fit=crop'],
        categoryId: '3',
        console: null,
        condition: 'sealed',
        complete: true,
        region: null,
        status: 'available',
        tags: ['new', 'featured'],
        createdAt: new Date('2026-01-22'),
    },
    {
        id: '4',
        name: 'Metal Gear Solid - PS1',
        price: 12000,
        description: 'Juego completo con caja y manual. Disco en buen estado, pequeñas marcas de uso normales.',
        images: ['https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=400&fit=crop'],
        categoryId: '1',
        console: 'PlayStation',
        condition: 'good',
        complete: true,
        region: 'NTSC',
        status: 'available',
        tags: ['offer', 'featured'],
        createdAt: new Date('2026-01-10'),
    },
    {
        id: '5',
        name: 'Game Boy Advance SP',
        price: 28000,
        description: 'GBA SP modelo AGS-101 con pantalla retroiluminada. Batería en buen estado.',
        images: ['https://images.unsplash.com/photo-1486401899868-0e435ed85128?w=400&h=400&fit=crop'],
        categoryId: '2',
        console: 'Game Boy',
        condition: 'like_new',
        complete: false,
        region: null,
        status: 'sold',
        tags: [],
        createdAt: new Date('2026-01-05'),
    },
    {
        id: '6',
        name: 'Sonic the Hedgehog - Sega Genesis',
        price: 6500,
        description: 'Cartucho original funcionando perfecto. Label en muy buen estado.',
        images: ['https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&h=400&fit=crop'],
        categoryId: '1',
        console: 'Sega Genesis',
        condition: 'good',
        complete: false,
        region: 'NTSC',
        status: 'available',
        tags: ['new'],
        createdAt: new Date('2026-02-01'),
    },
    {
        id: '7',
        name: 'Mario Kart 8 Deluxe - Switch',
        price: 9800,
        description: 'Juego físico en caja. Cartucho como nuevo, sin rayones.',
        images: ['https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=400&h=400&fit=crop'],
        categoryId: '1',
        console: 'Nintendo Switch',
        condition: 'like_new',
        complete: true,
        region: null,
        status: 'available',
        tags: ['featured'],
        createdAt: new Date('2026-02-05'),
    },
    {
        id: '8',
        name: 'Control DualShock 4 Negro',
        price: 7200,
        description: 'Control original Sony. Joysticks sin desgaste, todos los botones funcionando.',
        images: ['https://images.unsplash.com/photo-1600861194802-a2b11076bc51?w=400&h=400&fit=crop'],
        categoryId: '4',
        console: 'PlayStation 4',
        condition: 'good',
        complete: false,
        region: null,
        status: 'available',
        tags: ['offer'],
        createdAt: new Date('2026-02-10'),
    },
]

export const mockReviews: Review[] = [
    {
        id: '1',
        name: 'Lucas M.',
        rating: 5,
        text: 'Excelente vendedor, el juego llegó en perfectas condiciones y bien embalado. Muy recomendable!',
        visible: true,
        createdAt: new Date('2026-01-10'),
        date: '2026-01-10',
    },
    {
        id: '2',
        name: 'Sofía R.',
        rating: 5,
        text: 'Compré un amiibo sellado y llegó tal como lo mostraban. Responde rápido por WhatsApp. 100% confiable.',
        visible: true,
        createdAt: new Date('2026-01-15'),
        date: '2026-01-15',
    },
    {
        id: '3',
        name: 'Mateo G.',
        rating: 4,
        text: 'Buena atención y precio justo. Demoró un poco el envío pero avisó en todo momento. Volvería a comprar.',
        visible: true,
        createdAt: new Date('2025-12-20'),
        date: '2025-12-20',
    },
    {
        id: '4',
        name: 'Valentina P.',
        rating: 5,
        text: 'La consola llegó funcionando perfecto, igual que en las fotos. El trato fue muy amable. Muy recomendado!',
        visible: true,
        createdAt: new Date('2025-12-15'),
        date: '2025-12-15',
    },
]

export const mockBrands: Brand[] = [
    { id: '1', name: 'Nintendo', logo: null },
    { id: '2', name: 'PlayStation', logo: null },
    { id: '3', name: 'Xbox', logo: null },
    { id: '4', name: 'Sega', logo: null },
    { id: '5', name: 'Atari', logo: null },
    { id: '6', name: 'Capcom', logo: null },
    { id: '7', name: 'Konami', logo: null },
]